In [1]:
#import packages
import pandas as pd

In [2]:
#read in csv
bb = pd.read_csv(r"../data/Billboard1920.csv")
bb

                                                    song        date
0           /single/Thank%20U%2C%20Next/Ariana%20Grande/  2019-01-05
1                           /single/Without%20Me/Halsey/  2019-01-05
2      /single/All%20I%20Want%20For%20Christmas%20Is%...  2019-01-05
3                   /single/Sicko%20Mode/Travis%20Scott/  2019-01-05
4      /single/Sunflower%20%28Spider-Man%3A%20Into%20...  2019-01-05
...                                                  ...         ...
10395                   /single/Good%20Time/Niko%20Moon/  2020-12-26
10396  /single/Throat%20Baby%20%28Go%20Baby%29/BRS%20...  2020-12-26
10397                        /single/Errbody/Lil%20Baby/  2020-12-26
10398  /single/Favorite%20Time%20Of%20Year/Carrie%20U...  2020-12-26
10399               /single/Beautiful%20Trip/Kid%20Cudi/  2020-12-26

[10400 rows x 2 columns]

In [3]:
#strip /single
bb['song'] = bb['song'].str.replace('/single', '').str.strip('/').str.strip()
bb

                                                    song        date
0                    Thank%20U%2C%20Next/Ariana%20Grande  2019-01-05
1                                    Without%20Me/Halsey  2019-01-05
2      All%20I%20Want%20For%20Christmas%20Is%20You/Ma...  2019-01-05
3                            Sicko%20Mode/Travis%20Scott  2019-01-05
4      Sunflower%20%28Spider-Man%3A%20Into%20The%20Sp...  2019-01-05
...                                                  ...         ...
10395                            Good%20Time/Niko%20Moon  2020-12-26
10396         Throat%20Baby%20%28Go%20Baby%29/BRS%20Kash  2020-12-26
10397                                 Errbody/Lil%20Baby  2020-12-26
10398     Favorite%20Time%20Of%20Year/Carrie%20Underwood  2020-12-26
10399                        Beautiful%20Trip/Kid%20Cudi  2020-12-26

[10400 rows x 2 columns]

In [4]:
#split on /
bb[['track', 'artist']] = bb['song'].str.split('/', expand= True)
bb

,song,date,track,artist
0,Thank%20U%2C%20Next/Ariana%20Grande,2019-01-05,Thank%20U%2C%20Next,Ariana%20Grande
1,Without%20Me/Halsey,2019-01-05,Without%20Me,Halsey
2,All%20I%20Want%20For%20Christmas%20Is%20You/Ma...,2019-01-05,All%20I%20Want%20For%20Christmas%20Is%20You,Mariah%20Carey
3,Sicko%20Mode/Travis%20Scott,2019-01-05,Sicko%20Mode,Travis%20Scott
4,Sunflower%20%28Spider-Man%3A%20Into%20The%20Sp...,2019-01-05,Sunflower%20%28Spider-Man%3A%20Into%20The%20Sp...,Post%20Malone%20%26%20Swae%20Lee
...,...,...,...,...
10395,Good%20Time/Niko%20Moon,2020-12-26,Good%20Time,Niko%20Moon
10396,Throat%20Baby%20%28Go%20Baby%29/BRS%20Kash,2020-12-26,Throat%20Baby%20%28Go%20Baby%29,BRS%20Kash
10397,Errbody/Lil%20Baby,2020-12-26,Errbody,Lil%20Baby
10398,Favorite%20Time%20Of%20Year/Carrie%20Underwood,2020-12-26,Favorite%20Time%20Of%20Year,Carrie%20Underwood
10399,Beautiful%20Trip/Kid%20Cudi,2020-12-26,Beautiful%20Trip,Kid%20Cudi

In [5]:
#drop 'song' column
bb = bb.drop(columns='song')
bb

,date,track,artist
0,2019-01-05,Thank%20U%2C%20Next,Ariana%20Grande
1,2019-01-05,Without%20Me,Halsey
2,2019-01-05,All%20I%20Want%20For%20Christmas%20Is%20You,Mariah%20Carey
3,2019-01-05,Sicko%20Mode,Travis%20Scott
4,2019-01-05,Sunflower%20%28Spider-Man%3A%20Into%20The%20Sp...,Post%20Malone%20%26%20Swae%20Lee
...,...,...,...
10395,2020-12-26,Good%20Time,Niko%20Moon
10396,2020-12-26,Throat%20Baby%20%28Go%20Baby%29,BRS%20Kash
10397,2020-12-26,Errbody,Lil%20Baby
10398,2020-12-26,Favorite%20Time%20Of%20Year,Carrie%20Underwood
10399,2020-12-26,Beautiful%20Trip,Kid%20Cudi

In [21]:
#replace weird strings with spaces. supposed to strip end spaces too and replace X with spaces, but that doesnt work

replace_dict = {'%20':' ', '%3A':' ', '%28':' ', '%29':' ', '%26':' ', '%21':' ', '%27':' ', '%24':'$', '%22':' ', '%40':' ', '%2C':' ', '%2B':' ', '%2F':' ', '%2A':' ', '%3F':' ', ' X ':' ', ' x ':' ', 'Mr.':' '}
bb['track'] = bb['track'].replace(replace_dict, regex= True).str.strip()
bb['artist'] = bb['artist'].replace(replace_dict, regex= True).str.strip()
bb

,date,track,artist
0,2019-01-05,Thank U Next,Ariana Grande
1,2019-01-05,Without Me,Halsey
2,2019-01-05,All I Want For Christmas Is You,Mariah Carey
3,2019-01-05,Sicko Mode,Travis Scott
4,2019-01-05,Sunflower Spider-Man Into The Spider-Verse,Post Malone Swae Lee
...,...,...,...
10395,2020-12-26,Good Time,Niko Moon
10396,2020-12-26,Throat Baby Go Baby,BRS Kash
10397,2020-12-26,Errbody,Lil Baby
10398,2020-12-26,Favorite Time Of Year,Carrie Underwood
10399,2020-12-26,Beautiful Trip,Kid Cudi

In [22]:
#replace Xs separately, which works for some reason
bb['artist'] = bb['artist'].str.replace(' X ', ' ').str.replace(' x ', ' ')

In [23]:
#lets try to strip end spaces separately
bb['track'] = bb['track'].str.strip()
bb['artist'] = bb['artist'].str.strip()
# bb.to_csv('testXreplace', index= False)

In [24]:
#replace 'Featuring' with an empty string because the API throws an error if you don't
bb['artist'] = bb['artist'].str.replace('Featuring', '')
bb

,date,track,artist
0,2019-01-05,Thank U Next,Ariana Grande
1,2019-01-05,Without Me,Halsey
2,2019-01-05,All I Want For Christmas Is You,Mariah Carey
3,2019-01-05,Sicko Mode,Travis Scott
4,2019-01-05,Sunflower Spider-Man Into The Spider-Verse,Post Malone Swae Lee
...,...,...,...
10395,2020-12-26,Good Time,Niko Moon
10396,2020-12-26,Throat Baby Go Baby,BRS Kash
10397,2020-12-26,Errbody,Lil Baby
10398,2020-12-26,Favorite Time Of Year,Carrie Underwood
10399,2020-12-26,Beautiful Trip,Kid Cudi

In [25]:
#drop duplicates
nodupes = bb.drop_duplicates(subset= ('track', 'artist'))
nodupes

,date,track,artist
0,2019-01-05,Thank U Next,Ariana Grande
1,2019-01-05,Without Me,Halsey
2,2019-01-05,All I Want For Christmas Is You,Mariah Carey
3,2019-01-05,Sicko Mode,Travis Scott
4,2019-01-05,Sunflower Spider-Man Into The Spider-Verse,Post Malone Swae Lee
...,...,...,...
10384,2020-12-26,Heaven On Earth,Kid Cudi
10388,2020-12-26,Reminds Me Of You,The Kid LAROI Juice WRLD
10389,2020-12-26,Sad People,Kid Cudi
10390,2020-12-26,Damaged,Kid Cudi
10399,2020-12-26,Beautiful Trip,Kid Cudi

In [26]:
#export nodupes to csv
#nodupes.to_csv('../data/nodupesBillboard1920.csv', index= False)

In [27]:
#export clean to CSV with dupes
#bb.to_csv('../data/cleanBillboard1920.csv', index=False)

In [13]:
nodupes.iloc[101]

date              2019-01-12
track            Electricity
artist    Silk City Dua Lipa
Name: 161, dtype: object